[phases.setup]
# Install Python only
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip --break-system-packages",
  "python3 -m pip install -r requirements.txt --break-system-packages"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 wsgi_original:app"
