[phases.setup]
# Install Python only
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip --break-system-packages",
  "python3 -m pip install -r requirements.txt --break-system-packages"
]

[start]
cmd = "python radio_player_web.py"
